spring:
  application:
    name: relation-service

  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2